version: "3"
services:
  php:
    container_name: php
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    environment:
      MOCKSERVER_URL: 'http://mockserver:1080'
    volumes:
      - .:/app
    tty: true
  mockserver:
    container_name: mockserver
    image: mockserver/mockserver
    environment:
      MOCKSERVER_LOG_LEVEL: ${MOCKSERVER_LOG_LEVEL}
    ports:
      - "1080:1080"