version: "3"
services:
  php:
    container_name: php
    build:
      context: docker/php/
    environment:
      MOCKSERVER_URL: 'http://mockserver:1080'
      PHP_IDE_CONFIG: 'serverName=host.docker.internal'
      XDEBUG_TRIGGER: 1
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - .:/app
    tty: true
  mockserver:
    container_name: mockserver
    image: mockserver/mockserver
    environment:
      MOCKSERVER_LOG_LEVEL: ${MOCKSERVER_LOG_LEVEL}
    ports:
      - "1080:1080"