version: "3"
services:
  php:
    container_name: php
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - .:/app
    tty: true
  mockserver:
    container_name: mockserver
    image: mockserver/mockserver
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /expectations/**.json
      MOCKSERVER_LOG_LEVEL: ${MOCKSERVER_LOG_LEVEL}
    ports:
      - "1080:1080"
    volumes:
      - ./docker/mockserver/expectations:/expectations